// Generated by npm run catalog; do not edit manually.
export const catalog = {
  "snapshot": "2026-10-02T08:26:52+00:00",
  "method_uuid": "6209b35f-9447-40b5-b68c-a1099e3674a0",
  "method_name": "Climate change",
  "flow_uuid": "890a70b7-b677-4e2a-8a1b-7d017e0a10ae",
  "providers": [
    {
      "uuid": "0aa8c769-a04a-4e76-897a-2b1051cb9344",
      "name": "Electricity production ; Electricity mix ; China",
      "geo": "CN",
      "year": 2019
    },
    {
      "uuid": "a976ee9d-b890-4bc1-93d2-e649a723dd46",
      "name": "Electricity production ; Electricity mix ; Guangdong",
      "geo": "GD-CN",
      "year": 2019
    },
    {
      "uuid": "ed589f98-d6b7-42cf-89a4-19cb63e72ea2",
      "name": "Electricity production ; Electricity mix ; Zhejiang",
      "geo": "ZJ-CN",
      "year": 2019
    },
    {
      "uuid": "2f580165-5f1e-4314-8e3d-2009f57ad214",
      "name": "Electricity production ; Electricity mix ; Fujian",
      "geo": "FJ-CN",
      "year": 2019
    },
    {
      "uuid": "30558cec-4718-4eac-a400-85e45a276e73",
      "name": "Electricity production ; Electricity mix ; Sichuan",
      "geo": "SC-CN",
      "year": 2019
    },
    {
      "uuid": "1dbf3ef8-4cb4-4f82-9e0b-729040422300",
      "name": "Electricity production ; Electricity mix ; Inner Mongolia",
      "geo": "NMG-CN",
      "year": 2019
    }
  ]
};
